In [58]:
import numpy as np

students = np.array(["Aarushi", "Riya", "Neha", "Karan", "Rahul"])

marks = np.array([
    [85, 78, 92],
    [76, 88, 80],
    [90, 91, 89],
    [45, 50, 40],
    [60, 72, 68]
])
# Subjects:
# Math
# Science
# English

In [2]:
# Print all the student names
print("Student Name",students)

Student Name ['Aarushi' 'Riya' 'Neha' 'Karan' 'Rahul']


In [6]:
# total marks of all student
total_marks = marks.sum(axis = 1) 
print("Total_marks:", total_marks)

Total_marks: [255 244 270 135 200]


In [17]:
# Print total marks of each student
print(f"Total_marks of {students[0]} is {total_marks[0]}")
print(f"Total_marks of {students[1]} is {total_marks[1]}")
print(f"Total_marks of {students[2]} is {total_marks[2]}")
print(f"Total_marks of {students[3]} is {total_marks[3]}")
print(f"Total_marks of {students[4]} is {total_marks[4]}")

Total_marks of Aarushi is 255
Total_marks of Riya is 244
Total_marks of Neha is 270
Total_marks of Karan is 135
Total_marks of Rahul is 200


In [21]:
# Using loop
for i in range(len(students)):
    print(f"{students[i]}'s marks: {total_marks[i]}")

Aarushi's marks: 255
Riya's marks: 244
Neha's marks: 270
Karan's marks: 135
Rahul's marks: 200


In [30]:
# Print average marks of each student
avg_marks = marks.mean(axis=1)
print(np.round(avg_marks,2))

[85.   81.33 90.   45.   66.67]


In [31]:
# Find topper of the class
Topper = total_marks.max(axis = 0)
print(Topper)

270


In [33]:
topper_index = total_marks.argmax(axis = 0)
print(f"Topper: {students[topper_index]}")
print(f"Marks: {total_marks[topper_index]}")

Topper: Neha
Marks: 270


In [34]:
# Find student with lowest marks
lowest_index = total_marks.argmin()
print(f"Name(lowest_marks): {students[lowest_index]}")
print(f"Marks: {total_marks[lowest_index]}")

Name(lowest_marks): Karan
Marks: 135


In [37]:
# Print subject-wise average
# Meaning:
# average marks in Math
# average marks in Science
# average marks in English
avg_marks_sw= marks.mean(axis=0)
print(avg_marks_sw)

[71.2 75.8 73.8]


In [40]:
subjects = np.array(["Maths","Science","English"])
for i in range(len(avg_marks_sw)):
    print(f"Average marks in {subjects[i]} is {avg_marks_sw[i]}")

Average marks in Maths is 71.2
Average marks in Science is 75.8
Average marks in English is 73.8


In [41]:
# Find highest marks in each subject
highest_marks = marks.max(axis = 0)
print(highest_marks)

[90 91 92]


In [50]:
mask = avg_marks>80
print(mask)
for i in range (len(students)):
    if mask[i]== True:
        print((f"{students[i]} got above average mark 80: {np.round(avg_marks[i],2)}",))

[ True  True  True False False]
('Aarushi got above average mark 80: 85.0',)
('Riya got above average mark 80: 81.33',)
('Neha got above average mark 80: 90.0',)


In [56]:
mask = avg_marks<40
print(mask)
for i in range (len(students)):
    if mask[i]== True:
        print((f"{students[i]} got fail: {np.round(avg_marks[i],2)}",))

[False False False False False]


In [69]:
# Calculate percentage of each student
max_marks = 300
per_mark = (total_marks/max_marks)*100
for i in range (len(students)):
    print(f"{students[i]}'s Percentage: {per_mark[i]:.2f}%")

Aarushi's Percentage: 85.00%
Riya's Percentage: 81.33%
Neha's Percentage: 90.00%
Karan's Percentage: 45.00%
Rahul's Percentage: 66.67%


In [117]:
for i in range(len(students)):
     if (per_mark[i]>= 85):
         grade = "A"
         print(f"{students[i]} got {grade} grade")
     elif (70<=per_mark[i]< 85):
         grade = "B"
         print(f"{students[i]} got {grade} grade")
     elif (50<=per_mark[i]< 70):
         grade = "C"
         print(f"{students[i]} got {grade} grade")    
     else:
         grade = "D"
         print(f"{students[i]} got {grade} grade") 
        

Aarushi got A grade
Riya got B grade
Neha got A grade
Karan got D grade
Rahul got C grade


In [99]:
#Broadcasting
grace_marks = marks+5
print(grace_marks)

[[90 83 97]
 [81 93 85]
 [95 96 94]
 [50 55 45]
 [65 77 73]]


In [110]:
sort_marks = np.sort(total_marks,axis = 0)
print(sort_marks)

[135 200 244 255 270]


In [100]:
print(f"shaped = {marks.shape}")

shaped = (5, 3)


In [102]:
# Convert it into a single row:
reshaped = marks.reshape(3,5)
print(reshaped)

[[85 78 92 76 88]
 [80 90 91 89 45]
 [50 40 60 72 68]]


In [103]:
print("Old shape:", marks.shape)
print("New shape:", reshaped.shape)

Old shape: (5, 3)
New shape: (3, 5)


In [104]:
# Generate Random Marks Dataset
random_marks = np.random.randint(35, 101, size = (5,3))
print(random_marks)

[[36 93 91]
 [94 83 56]
 [56 80 46]
 [37 62 87]
 [62 59 51]]


In [125]:
# Report Card
for i in range(len(students)):
    if per_mark[i] >= 85:
        grade = "A"

    elif 70 <= per_mark[i] < 85:
        grade = "B"

    elif 50 <= per_mark[i] < 70:
        grade = "C"

    else:
        grade = "D"

    print(f"{students[i]} -> Total: {total_marks[i]} | Percentage: {per_mark[i]:.2f}% | Grade: {grade}")
   

Aarushi -> Total: 255 | Percentage: 85.00% | Grade: A
Riya -> Total: 244 | Percentage: 81.33% | Grade: B
Neha -> Total: 270 | Percentage: 90.00% | Grade: A
Karan -> Total: 135 | Percentage: 45.00% | Grade: D
Rahul -> Total: 200 | Percentage: 66.67% | Grade: C
